import type { Metadata } from 'next'
import './globals.css'
import Navigation from './ui/molecules/Navigation/Navigation'
import { albert } from './ui/fonts'
import TopBarNavigation from './ui/molecules/Navigation/TopBarNavigation'
import { CartProvider } from './providers/mainProvider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={albert.className}>
        <CartProvider>
          <TopBarNavigation />
          <Navigation />
          {children}
          <div id="modal-root"></div>
        </CartProvider>
      </body>
    </html>
  )
}
