import type { Metadata } from 'next'
import Navigation from './ui/molecules/Navigation/Navigation'
import { albert, outfit } from './ui/fonts'
import TopBarNavigation from './ui/molecules/Navigation/TopBarNavigation'
import { CartProvider } from './providers/mainProvider'
import './globals.css'
import "react-responsive-carousel/lib/styles/carousel.min.css"

export const metadata: Metadata = {
  title: {
    template: '%s | Happy Cat Tye Dye',
    default: 'Happy Cat Tye Dye',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={albert.className}>
        <CartProvider>
          <TopBarNavigation />
          <Navigation />
          <main className={outfit.variable}>
            {children}
            <div id="modal-root"></div>
          </main>
        </CartProvider>
      </body>
    </html>
  )
}
